map_type: costmap

obstacle_range: 5.0 # 2.0
raytrace_range: 8.0 # 3.0

transform_tolerance: 0.5 # 0.0
expected_update_rate: 10

robot_radius: 0.4 # 0.3
inflation_radius: 0.3 # 0.3
cost_scaling_factor: 5.0

max_obstacle_height: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: hokuyo
  data_type: LaserScan
  #topic: /where_am_i/laser/scan
  topic: scan
  marking: true
  clearing: true
  # https://answers.ros.org/question/119051/local-costmap-empty-using-move_base_node/
  min_obstacle_height: 0
  max_obstacle_height: 3
  #obstacle_range: 6
  #raytrace_range: 12

